# Generated by Django 5.0 on 2024-01-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_order_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='update_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
